### ISSUE TITLE
An error occurs after the configuration is started

### ISSUE THREAD

**Issue by phk422** [drwpow/vite-plugin-lqip#1]
![image](https://github.com/drwpow/vite-plugin-lqip/assets/59734322/c6f76389-f2f8-4acb-bb08-a856c7421f95)

**Comment by drwpow** [comment]
That error is caused by using legacy CJS modules in Node. It’s recommended to update your project to use modern ESM by adding `"type": "module"` to `package.json` ([docs](https://nodejs.org/api/packages.html#determining-module-system))

If that’s not possible, then this package could look into shipping a legacy CJS build for those that haven’t updated.

**Comment by phk422** [comment]
I have tried to use "type": "module" to solve the problem, but many dependencies in the project are still cjs, can I support cjs？

**Comment by phk422** [comment]
> That error is caused by using legacy CJS modules in Node. It’s recommended to update your project to use modern ESM by adding `"type": "module"` to `package.json` ([docs](https://nodejs.org/api/packages.html#determining-module-system))
> 
> If that’s not possible, then this package could look into shipping a legacy CJS build for those that haven’t updated.



> That error is caused by using legacy CJS modules in Node. It’s recommended to update your project to use modern ESM by adding `"type": "module"` to `package.json` ([docs](https://nodejs.org/api/packages.html#determining-module-system))
> 
> If that’s not possible, then this package could look into shipping a legacy CJS build for those that haven’t updated.

I have tried to use "type": "module" to solve the problem, but many dependencies in the project are still cjs, can I support cjs？

**Comment by phk422** [comment]
> That error is caused by using legacy CJS modules in Node. It’s recommended to update your project to use modern ESM by adding `"type": "module"` to `package.json` ([docs](https://nodejs.org/api/packages.html#determining-module-system))
> 
> If that’s not possible, then this package could look into shipping a legacy CJS build for those that haven’t updated.

I have tried to use "type": "module" to solve the problem, but many dependencies in the project are still cjs, could you consider supporting cjs?

**Comment by drwpow** [comment]
Added a CJS build in the latest version. If you could give it a try, please let me know if you encounter any additional errors!

**Comment by phk422** [comment]
Thank you very much! This problem has been solved, but now I have encountered a new problem. I raised an issue and tried to solve it myself, and I passed the test on my computer. I hope you can check whether other problems will be caused by this solution.
